name: Deploy to SFTP Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy to SFTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ps396065.dreamhostps.com }}
          username: ${{ secrets.quantum_social }}
          password: ${{ secrets.!LSVMy%u7VmL }}
          remote_dir: /path/to/your/remote/directory
          local_dir: .
          exclude: .git*
